# Generated by Django 2.2.5 on 2019-09-29 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laba1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
